name: Publish

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.0
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Install deps
        run: pnpm install

      - name: Cache build files
        uses: actions/cache@v2
        env:
          cache-name: cache-build-files
        with:
          path: |
            target
            core
            main
            umd
            unpkg
          key: ${{ env.cache-name }}-${{ github.sha }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
