name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: npm version ?
        required: true
        default: patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup git
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Version up
        run: npm version ${{ github.event.inputs.version }}
      - run: |
          git push origin
          git push origin --tags
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Install deps
        run: pnpm install

      - name: Cache build files
        uses: actions/cache@v2
        env:
          cache-name: cache-build-files
        with:
          path: |
            umd
            cjs
            esm
            target
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}

      - name: Build packages
        run: pnpm make

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
